package dev.blackoutburst.game.utils

enum class Textures(val file: String) {
    ERROR("blocks/error.png"),
    GRASS_TOP("blocks/grass_top.png"),
    GRASS_SIDE("blocks/grass_side.png"),
    DIRT("blocks/dirt.png"),
    STONE("blocks/stone.png"),
    OAK_LOG_TOP("blocks/log_oak_top.png"),
    OAK_SIDE("blocks/log_oak.png"),
    OAK_LEAVES("blocks/leaves_oak.png"),
    GLASS("blocks/glass.png"),
    WATER("blocks/water.png"),
    SAND("blocks/sand.png"),
    SNOW("blocks/snow.png"),
    OAK_PLANKS("blocks/planks_oak.png"),
    STONE_BRICKS("blocks/stonebrick.png"),
    NETHERRACK("blocks/netherrack.png"),
    GOLD_BLOCK("blocks/gold_block.png"),
    PACKED_ICE("blocks/ice_packed.png"),
    LAVA("blocks/lava.png"),
    BARREL_TOP("blocks/barrel_top.png"),
    BARREL_SIDE("blocks/barrel_side.png"),
    BARREL_BOTTOM("blocks/barrel_bottom.png"),
    BOOKSHELF("blocks/bookshelf.png"),
}